name: HTTP Triggered Workflow

on:
  repository_dispatch:
    types: [http-trigger]

jobs:
  handleRequest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run app.js
        run: node app.js
        env:
          CHANNEL_ID: ${{ secrets.STRIPE_PUBLIC_KEY }}
          BOT_TOKEN: ${{ secrets.STRIPE_SECRET_KEY }}
